# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout MagicMirror² repo
        uses: actions/checkout@v4
        with:
          repository: MichMich/MagicMirror
          path: MagicMirror

      - name: Checkout Module repo
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-bunq

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MagicMirror²
        run: |
          cd MagicMirror
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm ci
      - name: Run tests
        run: |
          cd MagicMirror/modules/MMM-bunq
          npm ci
          npm run test
